# Generated by Django 5.1.7 on 2025-03-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PovertyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=20)),
                ('household_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('family_members', models.PositiveIntegerField(blank=True, null=True)),
                ('reason_for_poverty', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'poor'}, on_delete=django.db.models.deletion.CASCADE, related_name='poor_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(max_length=50)),
                ('assistance_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_records', to='users.user')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_records', to='poverty.povertyapplication')),
            ],
        ),
    ]
