# Generated by Django 5.2 on 2025-04-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poverty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='povertyapplication',
            options={'ordering': ['-application_date']},
        ),
    ]
