# Generated by Django 5.2 on 2025-04-14 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poverty', '0002_alter_povertyapplication_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='povertyapplication',
            options={'ordering': ['-created_at'], 'verbose_name': '贫困户申请', 'verbose_name_plural': '贫困户申请'},
        ),
        migrations.RemoveField(
            model_name='povertyapplication',
            name='application_date',
        ),
        migrations.AddField(
            model_name='povertyapplication',
            name='content',
            field=models.TextField(default='空', verbose_name='申请内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='povertyapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='povertyapplication',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='povertyapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='povertyapplication',
            name='title',
            field=models.CharField(default='默认标题', max_length=200, verbose_name='申请标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='povertyapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='povertyapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poverty_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
