# Generated by Django 5.2 on 2025-04-17 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poverty', '0003_alter_povertyapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancerecord',
            options={'ordering': ['-created_at'], 'verbose_name': '帮扶项目', 'verbose_name_plural': '帮扶项目'},
        ),
        migrations.RemoveField(
            model_name='assistancerecord',
            name='application',
        ),
        migrations.RemoveField(
            model_name='assistancerecord',
            name='assistance_date',
        ),
        migrations.RemoveField(
            model_name='assistancerecord',
            name='assistance_type',
        ),
        migrations.RemoveField(
            model_name='assistancerecord',
            name='details',
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='contact_person',
            field=models.CharField(default='', max_length=100, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='content',
            field=models.TextField(default='', verbose_name='项目内容'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='报名截止日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='description',
            field=models.TextField(default='', verbose_name='项目简介'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='结束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assistance_images/', verbose_name='项目图片'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开始日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已结束')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='assistancerecord',
            name='supporter',
            field=models.ForeignKey(limit_choices_to={'user_type': 'social'}, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
