# Generated by Django 5.1.6 on 2025-03-08 01:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('payment_status', models.CharField(default='待支付', max_length=20, verbose_name='支付状态')),
                ('payment_method', models.CharField(max_length=50, verbose_name='支付方式')),
                ('delivery_status', models.CharField(default='待发货', max_length=20, verbose_name='发货状态')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流单号')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('poor_household', '贫困户'), ('admin', '管理员'), ('company', '社会公司'), ('volunteer', '志愿者')], default='poor_household', max_length=20, verbose_name='用户类型')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='backend_user_groups', related_query_name='backend_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='backend_user_permissions', related_query_name='backend_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('product_description', models.TextField(verbose_name='商品描述')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('product_stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.order', verbose_name='订单')),
                ('logistics_company', models.CharField(max_length=100, verbose_name='物流公司')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='物流单号')),
                ('logistics_status', models.CharField(max_length=50, verbose_name='物流状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流信息',
                'verbose_name_plural': '物流信息',
            },
        ),
        migrations.CreateModel(
            name='PoorHousehold',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.user', verbose_name='用户')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证号')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系方式')),
                ('address', models.TextField(verbose_name='家庭住址')),
                ('family_size', models.IntegerField(verbose_name='家庭人口')),
                ('poverty_type', models.CharField(max_length=50, verbose_name='贫困类型')),
                ('application_materials', models.TextField(blank=True, null=True, verbose_name='申请材料')),
                ('application_status', models.CharField(default='待审核', max_length=20, verbose_name='申请状态')),
            ],
            options={
                'verbose_name': '贫困户信息',
                'verbose_name_plural': '贫困户信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='买家'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(verbose_name='消息内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='backend.user', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='backend.user', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '客服消息',
                'verbose_name_plural': '客服消息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='product',
            name='poor_household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poorhousehold', verbose_name='贫困户'),
        ),
        migrations.CreateModel(
            name='MaterialAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=100, verbose_name='捐赠方')),
                ('material_type', models.CharField(max_length=50, verbose_name='物资类型')),
                ('material_quantity', models.CharField(max_length=50, verbose_name='物资数量')),
                ('assistance_time', models.DateField(verbose_name='援助时间')),
                ('assistance_status', models.CharField(default='待发放', max_length=20, verbose_name='发放状态')),
                ('poor_household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poorhousehold', verbose_name='贫困户')),
            ],
            options={
                'verbose_name': '物资援助信息',
                'verbose_name_plural': '物资援助信息',
            },
        ),
        migrations.CreateModel(
            name='EducationAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=100, verbose_name='资助方')),
                ('assistance_type', models.CharField(max_length=50, verbose_name='资助类型')),
                ('assistance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='资助金额')),
                ('academic_year', models.CharField(max_length=20, verbose_name='资助学年')),
                ('assistance_status', models.CharField(default='待资助', max_length=20, verbose_name='资助状态')),
                ('poor_household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poorhousehold', verbose_name='贫困户')),
            ],
            options={
                'verbose_name': '教育资助信息',
                'verbose_name_plural': '教育资助信息',
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_time', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('audit_result', models.BooleanField(verbose_name='审核结果')),
                ('audit_opinion', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='审核人')),
                ('poor_household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poorhousehold', verbose_name='贫困户')),
            ],
            options={
                'verbose_name': '贫困户审核记录',
                'verbose_name_plural': '贫困户审核记录',
            },
        ),
        migrations.CreateModel(
            name='AssistanceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(max_length=50, verbose_name='帮扶类型')),
                ('assistance_provider', models.CharField(max_length=100, verbose_name='帮扶提供方')),
                ('assistance_content', models.TextField(verbose_name='帮扶内容')),
                ('assistance_time', models.DateField(verbose_name='帮扶时间')),
                ('assistance_status', models.CharField(default='待对接', max_length=20, verbose_name='帮扶状态')),
                ('poor_household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poorhousehold', verbose_name='贫困户')),
            ],
            options={
                'verbose_name': '帮扶对接信息',
                'verbose_name_plural': '帮扶对接信息',
            },
        ),
    ]
