# Generated by Django 5.2 on 2025-04-14 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='poor_applications/', verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '贫困户申请',
                'verbose_name_plural': '贫困户申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
